In [1]:
import numpy as np
import pandas as pd

In [2]:
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score
from sklearn.utils import shuffle
import pickle

In [3]:
df = pd.read_csv('data.csv', header=None)
df.drop(0, axis=1, inplace=True)
df = shuffle(df)

In [4]:
df

1         2         3         4         5         6         7    \
950  3.487376  0.762225  0.957889  1.197558  1.538595  1.573170  2.172735   
380  0.745184  0.263541  0.290803  0.281716  0.390767  0.490731  0.390767   
839  0.012419  0.000000  0.012419  0.007452  0.009935  0.029806  0.019871   
502  4.652264  2.302455  2.668584  3.668797  4.694998  5.394916  4.969306   
938  0.405078  0.111779  0.157092  0.192150  0.292118  0.306399  0.585094   
..        ...       ...       ...       ...       ...       ...       ...   
292  0.013298  0.000000  0.000000  0.265957  0.186170  0.492021  0.531915   
585  0.000000  0.000000  0.000000  0.000000  0.008818  0.000000  0.008818   
959  3.034797  0.886379  1.216124  1.483224  2.149843  2.641677  4.374748   
712  0.119409  0.016746  0.019796  0.023076  0.028601  0.032284  0.033953   
665  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          8         9         10   ...          760          761          762  \
950  2.716507  2.872881  3.498377  ...    16.000000    23.000000    14.000000   
380  0.472555  0.563431  0.636132  ...     0.000000     0.000000     0.000000   
839  0.017387  0.024839  0.029806  ...     9.000001    10.000001    16.000002   
502  5.740833  5.277686  6.205713  ...     0.000000     0.000000     0.000000   
938  0.697894  1.095348  1.260868  ...     0.000000     0.000000     0.000000   
..        ...       ...       ...  ...          ...          ...          ...   
292  1.183511  0.398936  1.236702  ...     0.000000     0.000000     0.000000   
585  0.000000  0.070547  0.026455  ...     0.000000     0.000000     0.000000   
959  5.248467  7.583182  5.603116  ...   438.999970   452.999970   467.999970   
712  0.039362  0.048224  0.051274  ...  2674.000000  3032.000000  3296.000000   
665  0.000000  0.000000  0.000000  ...     0.000000     0.000000     0.000000   

             763          764          765          766          767  \
950    18.000000    14.000000    16.000000     6.000000    14.000000   
380     0.000000     0.000000     0.000000     0.000000     0.000000   
839    19.000002    13.000002    14.000002    19.000002    16.000002   
502     0.000000     0.000000     0.000000     0.000000     0.000000   
938     0.000000     0.000000     0.000000     0.000000     0.000000   
..           ...          ...          ...          ...          ...   
292     0.000000     0.000000     0.000000     0.000000     0.000000   
585     0.000000     0.000000     0.000000     0.000000     0.000000   
959   337.999970   411.999970   364.999970   440.999970   372.999970   
712  3558.000000  2404.000000  3530.000000  3095.000000  2009.000000   
665     0.000000     0.000000     0.000000     0.000000     0.000000   

              768  769  
950     69.000000  1.0  
380      0.000000  1.0  
839     61.000008  0.0  
502      0.000000  1.0  
938      0.000000  0.0  
..            ...  ...  
292      0.000000  0.0  
585      0.000000  0.0  
959   6677.999500  1.0  
712  19809.000000  0.0  
665      0.000000  0.0  

[1025 rows x 769 columns]

In [5]:
df[769].value_counts()

0.0    604
1.0    409
Name: 769, dtype: int64

In [6]:
# controllo se esistono valori nulli
# print(df.isnull().values.any())
# guardo dove sono i valori nulli e quanti sono
df.dropna(inplace=True)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=0.3, random_state=0)

In [8]:
df.iloc[:,-1]

950    1.0
380    1.0
839    0.0
502    1.0
938    0.0
      ... 
292    0.0
585    0.0
959    1.0
712    0.0
665    0.0
Name: 769, Length: 1013, dtype: float64

In [9]:
df.iloc[:,:-1]

1         2         3         4         5         6         7    \
950  3.487376  0.762225  0.957889  1.197558  1.538595  1.573170  2.172735   
380  0.745184  0.263541  0.290803  0.281716  0.390767  0.490731  0.390767   
839  0.012419  0.000000  0.012419  0.007452  0.009935  0.029806  0.019871   
502  4.652264  2.302455  2.668584  3.668797  4.694998  5.394916  4.969306   
938  0.405078  0.111779  0.157092  0.192150  0.292118  0.306399  0.585094   
..        ...       ...       ...       ...       ...       ...       ...   
292  0.013298  0.000000  0.000000  0.265957  0.186170  0.492021  0.531915   
585  0.000000  0.000000  0.000000  0.000000  0.008818  0.000000  0.008818   
959  3.034797  0.886379  1.216124  1.483224  2.149843  2.641677  4.374748   
712  0.119409  0.016746  0.019796  0.023076  0.028601  0.032284  0.033953   
665  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          8         9         10   ...          759          760          761  \
950  2.716507  2.872881  3.498377  ...    16.000000    16.000000    23.000000   
380  0.472555  0.563431  0.636132  ...     0.000000     0.000000     0.000000   
839  0.017387  0.024839  0.029806  ...    16.000002     9.000001    10.000001   
502  5.740833  5.277686  6.205713  ...     0.000000     0.000000     0.000000   
938  0.697894  1.095348  1.260868  ...     0.000000     0.000000     0.000000   
..        ...       ...       ...  ...          ...          ...          ...   
292  1.183511  0.398936  1.236702  ...     0.000000     0.000000     0.000000   
585  0.000000  0.070547  0.026455  ...     0.000000     0.000000     0.000000   
959  5.248467  7.583182  5.603116  ...   520.999940   438.999970   452.999970   
712  0.039362  0.048224  0.051274  ...  2977.000000  2674.000000  3032.000000   
665  0.000000  0.000000  0.000000  ...     0.000000     0.000000     0.000000   

             762          763          764          765          766  \
950    14.000000    18.000000    14.000000    16.000000     6.000000   
380     0.000000     0.000000     0.000000     0.000000     0.000000   
839    16.000002    19.000002    13.000002    14.000002    19.000002   
502     0.000000     0.000000     0.000000     0.000000     0.000000   
938     0.000000     0.000000     0.000000     0.000000     0.000000   
..           ...          ...          ...          ...          ...   
292     0.000000     0.000000     0.000000     0.000000     0.000000   
585     0.000000     0.000000     0.000000     0.000000     0.000000   
959   467.999970   337.999970   411.999970   364.999970   440.999970   
712  3296.000000  3558.000000  2404.000000  3530.000000  3095.000000   
665     0.000000     0.000000     0.000000     0.000000     0.000000   

             767           768  
950    14.000000     69.000000  
380     0.000000      0.000000  
839    16.000002     61.000008  
502     0.000000      0.000000  
938     0.000000      0.000000  
..           ...           ...  
292     0.000000      0.000000  
585     0.000000      0.000000  
959   372.999970   6677.999500  
712  2009.000000  19809.000000  
665     0.000000      0.000000  

[1013 rows x 768 columns]

In [10]:
from sklearn import svm

In [11]:
clf = svm.SVC(class_weight='balanced', C=950)
clf.fit(X_train, y_train)

SVC(C=950, break_ties=False, cache_size=200, class_weight='balanced', coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [12]:
y_pred = clf.predict(X_train)
acc = metrics.accuracy_score(y_train, y_pred)
print('training')
print(acc)

training
0.9887165021156559


In [13]:
y_pred = clf.predict(X_test)
acc = metrics.accuracy_score(y_test, y_pred)
print('test')
print(acc)
metrics.confusion_matrix(y_test, y_pred)

test
0.8717105263157895


array([[175,  14],
       [ 25,  90]], dtype=int64)

In [14]:
df = pd.read_csv('data.csv', header=None)
df.drop(0, axis=1, inplace=True)
df.dropna(inplace=True)
df = shuffle(df)

In [15]:
clf = svm.SVC(class_weight='balanced', C=950)
results = cross_val_score(clf, df.drop([769], axis=1), df[769], cv=10)
print('SVM')
print(results)
print(results.mean())

SVM
[0.88235294 0.90196078 0.83333333 0.89108911 0.9009901  0.85148515
 0.88118812 0.96039604 0.85148515 0.93069307]
0.8884973791496795


df = pd.read_csv('data.csv', header=None)
df.drop(0, axis=1, inplace=True)
df.dropna(inplace=True)
df = shuffle(df)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=0.3, random_state=0)
from sklearn.linear_model import LogisticRegression

In [16]:
print('Logistic Regression')
lg = LogisticRegression(random_state=0).fit(X_train, y_train)

y_pred = lg.predict(X_train)
acc = metrics.accuracy_score(y_train, y_pred)
print('training')
print(acc)


y_pred = lg.predict(X_test)
acc = metrics.accuracy_score(y_test, y_pred)
print('test')
print(acc)
metrics.confusion_matrix(y_test, y_pred)

Logistic Regression


NameError: name 'LogisticRegression' is not defined

In [17]:
df = pd.read_csv('data.csv', header=None)
df.drop(0, axis=1, inplace=True)
df.dropna(inplace=True)
df = shuffle(df)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=0.3, random_state=0)

In [18]:
clf = svm.SVC(class_weight='balanced')
clf.fit(df.drop([769], axis=1), df[769])

SVC(C=1.0, break_ties=False, cache_size=200, class_weight='balanced', coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
y_pred = clf.predict(X_test)
acc = metrics.accuracy_score(y_test, y_pred)
print('test')
print(acc)
metrics.confusion_matrix(y_test, y_pred)

test
0.9078947368421053


array([[176,   9],
       [ 19, 100]], dtype=int64)

In [20]:
with open('C:/Users/fabio/Desktop/Mag1.2/VisionAndCognitiveSystem/Project/vision_final_project/svm/model.pickle', 'wb') as model_file:
    pickle.dump(clf, model_file)

In [21]:
with open('../svm/model.pickle', 'rb') as model_file:

    clf2 = pickle.load(model_file)

In [22]:
clf2.predict(X_test)

array([1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 1., 1.